apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: core
  labels:
    name: core
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: core-apps
    spec:
      containers:
      - name: core-app
        image: vmware/harbor-core:v1.2.0
        imagePullPolicy: IfNotPresent
        env:
          - name: CONFIG_PATH
            valueFrom:
              configMapKeyRef:
               name: harbor-core-config
               key: CONFIG_PATH
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
               name: harbor-core-config
               key: LOG_LEVEL
          - name: CORE_SECRET
            valueFrom:
              configMapKeyRef:
               name: harbor-core-config
               key: CORE_SECRET
          - name: JOBSERVICE_SECRET
            valueFrom:
              configMapKeyRef:
               name: harbor-core-config
               key: JOBSERVICE_SECRET
          - name: GODEBUG
            valueFrom:
              configMapKeyRef:
               name: harbor-core-config
               key: GODEBUG
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/core
      volumes:
      - name: config
        configMap:
          name: harbor-core-config
          items:
          - key: config
            path: app.conf
          - key: pkey
            path: private_key.pem
          - key: SECRET_KEY
            path: key
