apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jobservice
  labels:
    name: jobservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jobservice-apps
    spec:
      containers:
      - name: jobservice-app
        image: vmware/harbor-jobservice:v1.2.0
        imagePullPolicy: IfNotPresent
        env:
          - name: CORE_SECRET
            valueFrom:
              configMapKeyRef:
               name: harbor-jobservice-config
               key: CORE_SECRET
          - name: JOBSERVICE_SECRET
            valueFrom:
              configMapKeyRef:
               name: harbor-jobservice-config
               key: JOBSERVICE_SECRET
          - name: CONFIG_PATH
            valueFrom:
              configMapKeyRef:
               name: harbor-jobservice-config
               key: CONFIG_PATH
          - name: LOG_LEVEL
            valueFrom:
              configMapKeyRef:
               name: harbor-jobservice-config
               key: LOG_LEVEL
          - name: GODEBUG
            valueFrom:
              configMapKeyRef:
               name: harbor-jobservice-config
               key: GODEBUG
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/jobservice
        - name: logs
          mountPath: /var/log/jobs
      volumes:
      - name: config
        configMap:
          name: harbor-jobservice-config
          items:
          - key: config
            path: app.conf
      - name: logs
        persistentVolumeClaim:
          claimName: log-pvc
