apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
data:
  CORE_SECRET: "{{core_secret}}"
  JOBSERVICE_SECRET: "{{jobservice_secret}}"
  SECRET_KEY: "{{secret_key}}"
  MAX_JOB_WORKERS: "{{max_job_workers}}"
  LOG_LEVEL: debug
  GODEBUG: netdns=cgo
  CONFIG_PATH: /etc/jobservice/app.conf
  config: |
    appname = jobservice
    runmode = dev
    [dev]
    httpport = 80
