apiVersion: v1
kind: Service
metadata:
  name: "{{ template "harbor.fullname" . }}-ui"
  labels:
{{ include "harbor.labels" . | indent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: ui
