apiVersion: v1
kind: ReplicationController
metadata:
  name: ui-rc
  labels:
    name: ui-rc
spec:
  replicas: 1
  selector:
    name: ui-apps
  template:
    metadata:
      labels:
        name: ui-apps
    spec:
      containers:
      - name: ui-app
        image: vmware/harbor-ui:v1.2.0
        imagePullPolicy: IfNotPresent
        env:
          - name: CONFIG_PATH
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: CONFIG_PATH
          - name: LOG_LEVEL
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: LOG_LEVEL
          - name: UI_SECRET
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: UI_SECRET
          - name: JOBSERVICE_SECRET
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: JOBSERVICE_SECRET
          - name: GODEBUG
            valueFrom: 
              configMapKeyRef: 
               name: harbor-ui-config
               key: GODEBUG
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/ui
      volumes:
      - name: config
        configMap:
          name: harbor-ui-config
          items:
          - key: config
            path: app.conf
          - key: pkey
            path: private_key.pem
          - key: SECRET_KEY
            path: key
