---
#Protocol used to serve
protocol: "http"

#Config certification if use 'https' protocol
#https_config:
#  cert: "server.crt"
#  key: "server.key"

#Server listening port
port: 8080

#Worker pool
worker_pool:
  #Worker concurrency
  workers: $max_job_workers
  backend: "redis"
  #Additional config if use 'redis' backend
  redis_pool:
    #redis://[arbitrary_username:password@]ipaddress:port/database_index
    redis_url: $redis_url
    namespace: "harbor_job_service_namespace"
#Logger for job
logger:
  path: "/var/log/jobs"
  level: "INFO"
  archive_period: 14 #days
#Admin server endpoint
admin_server: "http://adminserver:8080/"
