apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.fullname" . }}-adminserver"
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: adminserver
type: Opaque
data:
  secretKey: {{ .Values.secretKey | b64enc | quote }}
  EMAIL_PWD: {{ .Values.adminserver.emailPwd | b64enc | quote }}
  HARBOR_ADMIN_PASSWORD: {{ .Values.adminserver.adminPassword | b64enc | quote }}
  MYSQL_PWD: {{ .Values.mysql.pass | b64enc | quote }}
  JOBSERVICE_SECRET: {{ .Values.jobservice.secret | b64enc | quote }}
  UI_SECRET: {{ .Values.ui.secret | b64enc | quote }}
{{ if .Values.clair.enabled }}
  CLAIR_DB_PASSWORD: {{ .Values.clair.postgresPassword | b64enc | quote }}
{{ end }}
  #LDAP_SEARCH_PWD: not-a-secure-password
