apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "harbor.fullname" . }}-ingress"
  labels:
{{ include "harbor.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  tls:
  - hosts:
    - "{{ .Values.externalDomain }}"
{{ if not .Values.insecureRegistry }}
    secretName: "{{ template "harbor.fullname" . }}-ingress"
{{ end }}
  rules:
  - host: "{{ .Values.externalDomain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "harbor.fullname" . }}-ui
          servicePort: 80
      - path: /v2
        backend:
          serviceName: {{ template "harbor.fullname" . }}-registry
          servicePort: 5000
      - path: /v1
        backend:
          serviceName: {{ template "harbor.fullname" . }}-fake-service
          servicePort: 5000
