apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.fullname" . }}-ingress"
  labels:
{{ include "helm.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsCrt | b64enc | quote }}
  tls.key: {{ .Values.tlsKey | b64enc | quote }}
  ca.crt: {{ .Values.caCrt | b64enc | quote }}
