apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.fullname" . }}-registry"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  httpSecret: {{ .Values.registry.httpSecret | b64enc | quote }}
  root.crt: {{ .Values.registry.rootCrt | b64enc | quote }}