{{ if .Values.notary.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "harbor.fullname" . }}-notary-server
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: notary-server
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "harbor.matchLabels" . | indent 6 }}
      component: notary-server
  template:
    metadata:
      labels:
{{ include "harbor.labels" . | indent 8 }}
        component: notary-server
    spec:
      containers:
      - name: notary-server
        image: {{ .Values.notary.server.image.repository }}:{{ .Values.notary.server.image.tag }}
        imagePullPolicy: {{ .Values.notary.server.image.pullPolicy }}
        resources:
{{ toYaml .Values.notary.server.resources | indent 10 }}
        env:
        - name: MIGRATIONS_PATH
          value: migrations/server/postgresql
        - name: DB_URL
          value: {{ template "harbor.database.notaryServer" . }}
        volumeMounts:
        - name: notary-config
          mountPath: /etc/notary
        - name: root-certificate
          mountPath: /root.crt
          subPath: tokenServiceRootCertBundle
      volumes:
      - name: notary-config
        configMap:
          name: "{{ template "harbor.fullname" . }}-notary"
      - name: root-certificate
        secret:
          secretName: "{{ template "harbor.fullname" . }}-ui"
    {{- with .Values.notary.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.notary.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.notary.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{ end }}
