version: '2'
services:
  ui:
    networks:
      harbor-clair:
        aliases:
          - harbor-ui
  jobservice:
    networks:
      - harbor-clair
  registry:
    networks:
      - harbor-clair
  postgres:
    networks:
      harbor-clair:
        aliases:
          - postgres
    container_name: clair-db
    image: vmware/postgresql:9.6.3-photon
    restart: always
    depends_on:
      - log
    env_file:
      ./common/config/clair/postgres_env
    volumes:
      - /data/clair-db:/var/lib/postgresql/data
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "clair-db"
  clair:
    networks:
      - harbor-clair
    container_name: clair
    image: quay.io/coreos/clair:v2.0.0
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./common/config/clair:/config
    command: [-config, /config/config.yaml]
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "clair"
networks:
  harbor-clair:
    external: false
