# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"
ignored = ["github.com/vmware/harbor/tests*"]

[[constraint]]
  name = "github.com/astaxie/beego"
  version = "=1.9.0"

[[constraint]]
  name = "github.com/dghubble/sling"
  version = "=1.1.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "=3.0.0"

[[constraint]]
  name = "github.com/docker/distribution"
  version = "=2.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/docker/libtrust"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "=1.3.0"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "=1.6.0"

[[constraint]]
  name = "github.com/opencontainers/go-digest"
  version = "=1.0.0-rc0"

[[constraint]]
  name = "gopkg.in/ldap.v2"
  version = "=2.5.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=1.2.0"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "=1.3.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "=1.6.0"

[[override]]
  name = "github.com/Sirupsen/logrus"
  version = "=1.0.5"

[[override]]
  name = "github.com/gorilla/context"
  version = "=1.1"

[[override]]
  name = "github.com/garyburd/redigo"
  version = "=1.6.0"