{{ if .Values.clair.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "harbor.fullname" . }}-clair
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: clair
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "harbor.matchLabels" . | indent 6 }}
      component: clair
  template:
    metadata:
      labels:
{{ include "harbor.labels" . | indent 8 }}
        component: clair
    spec:
      containers:
      - name: clair
        image: {{ .Values.clair.image.repository }}:{{ .Values.clair.image.tag }}
        imagePullPolicy: {{ .Values.clair.image.pullPolicy }}
        args: ["-insecure-tls", "-config", "/etc/clair/config.yaml"]
        resources:
{{ toYaml .Values.clair.resources | indent 10 }}
        ports:
        - containerPort: 6060
        volumeMounts:
        - name: clair-config
          mountPath: /etc/clair/config.yaml
          subPath: config.yaml
      volumes:
      - name: clair-config
        configMap:
          name: "{{ template "harbor.fullname" . }}-clair"
          items:
            - key: config.yaml
              path: config.yaml
    {{- with .Values.clair.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.clair.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.clair.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{ end }}
