name: CI

on:
  pull_request:
    # the paths is the same as the paths-ignore in CI.yml, they should be synced together
    paths:
      - 'docs/**'
      - '**.md'
      - 'tests/**'
      - '!tests/**.sh'
      - '!tests/apitests/**'
      - '!tests/ci/**'
      - '!tests/resources/**'
      - '!tests/robot-cases/**'
      - '!tests/robot-cases/Group1-Nightly/**'
  push:
    # the paths is the same as the paths-ignore in CI.yml, they should be synced together
    paths:
      - 'docs/**'
      - '**.md'
      - 'tests/**'
      - '!tests/**.sh'
      - '!tests/apitests/**'
      - '!tests/ci/**'
      - '!tests/resources/**'
      - '!tests/robot-cases/**'
      - '!tests/robot-cases/Group1-Nightly/**'

jobs:
  UTTEST:
    permissions:
      contents: read
    runs-on:
      - ubuntu-latest
    steps:
      - run: 'echo "No run required"'

  APITEST_DB:
    permissions:
      contents: read
    runs-on:
      - ubuntu-latest
    steps:
      - run: 'echo "No run required"'

  APITEST_DB_PROXY_CACHE:
    permissions:
      contents: read
    runs-on:
      - ubuntu-latest
    steps:
      - run: 'echo "No run required"'

  APITEST_LDAP:
    permissions:
      contents: read
    runs-on:
      - ubuntu-latest
    steps:
      - run: 'echo "No run required"'

  OFFLINE:
    permissions:
      contents: read
    runs-on:
      - ubuntu-latest
    steps:
      - run: 'echo "No run required"'

  UI_UT:
    permissions:
      contents: read
    runs-on:
      - ubuntu-latest
    steps:
      - run: 'echo "No run required"'
